version: '3.8'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080

  db:
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: itxwabizzdb
    container_name: database
    ports:
      - 3306:3306