version: '3.8'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - ${PORT}:${PORT}

  db:
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: database
    ports:
      - ${MYSQL_PORT}:3306