version: '3.8'
services:
  backend:
    build: .
    env_file:
    - .env
    container_name: backend
    ports:
      - ${PORT}:${PORT}

  db:
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
    - .env
    container_name: database
    ports:
      - ${MYSQL_PORT}:3306